# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

symmetricMatrix <- function(n, v) {
    .Call('randomMatRices_symmetricMatrix', PACKAGE = 'randomMatRices', n, v)
}

hermitianMatrix <- function(n, v) {
    .Call('randomMatRices_hermitianMatrix', PACKAGE = 'randomMatRices', n, v)
}

